import React from 'react'

export default function About() {
  return (
    <div>
        <p>HI THIS IS MY NEW APP WHICH I CREATED USING REACT. THE MAIN WORKING PRINCIPLE FOR THE APP IS IT CHANGES THE CHARACTERS TO UPPERCASE FROM LOWERCASE MOREOVER IT HAS A BONUS FEATURE WHICH SHOWS THE WORD COUNT AND ALSO THE TOTAL NUMBER OF CHARACTERS!!! PRETTY COOL HUHH!! 
I LIKE IT ALHAMDULILLAH</p>


    </div>
  )
}
